spring.application.name=Noto-back

# Connexion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/notoDB
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
#jwt.secret=ChangeMoiEnProductionAvecUneCleBase64GenereeAleatoirementEtSecurisee123456
jwt.secret=2a7JFfXGaz07cmczJcV0B9T5XIaW8JMRzhlw2BK436K
jwt.access-token-expiration=900000
# 15 minutes en ms
jwt.refresh-token-expiration=604800000
# 7 jours en ms

# CORS
app.cors.allowed-origins=http://localhost:4200

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html